
name: data-science
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scikit-learn
  - pytorch 
  - matplotlib
  - pip
  - pandas
  - seaborn
  - imbalanced-learn
  - mlxtend
  - statsmodels


    